export const EVENT_CHECK_PINTREE_EXTENSION_INSTALLED =
  "check-pintree-extension-installed"
export const EVENT_PINTREE_SYNC_BOOKMARKS = "pintree-sync-bookmarks"
export const EVENT_AUTH_STATUS = "AUTH_STATUS"
export const EVENT_SEND_BOOKMARKS = "SEND_BOOKMARKS"
export const EVENT_CONFIRM_PINTREE_EXTENSION_INSTALLED =
  "CONFIRM_PINTREE_EXTENSION_INSTALLED"
export const EVENT_PINTREE_BOOKMARKS_SYNCED = "PINTREE_BOOKMARKS_SYNCED"
export const EVENT_GET_TAB_INFO = "GET_TAB_INFO"
export const EVENT_SAVE_TAB_INFO = "SAVE_TAB_INFO"
